language: php
php:
  - '7.3'
os: linux
arch: arm64
dist: xenial
before_install:
  - composer install
  - npm install
  - ./node_modules/.bin/gulp testSupport
stages:
  - name: test
jobs:
  include:
    - stage: test
      name: test
      script:
        - ./vendor/bin/phpunit
